name: korekushon
description: Help you to track & organize your book collection
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0
  logger: ^1.1.0
  get_it: ^7.2.0
  dio: ^4.0.6
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.5
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
